#!/bin/bash

PIPE_VIDEO_PREFIX="/tmp/video"

BINPATH=`pwd`
export PATH=$BINPATH:$PATH

RTSPSERVER=rtspsvr
RTSPCLIENT=rtspclient
VCAPTURE=vcapture

PCMD=$1

fMsg() {
	echo -e "$1"
}

fInit() {
	fMsg "Execute fInit"
	for N in $(seq 0 3)
	do
		pipe_video=${PIPE_VIDEO_PREFIX}${N}.264
		[ -e "$pipe_video" ] && rm -rf $pipe_video
		mkfifo $pipe_video
	done
}

fStart() {
	fMsg "Execute fStart"
	echo "$RTSPSERVER &"
	$RTSPSERVER &
	args=''
	for N in $(seq 0 3)
	do
		dev_video="/dev/video$N"
		pipe_video=${PIPE_VIDEO_PREFIX}${N}.264
		if [ -e "$dev_video" ] ; then
			echo "$VCAPTURE --dev=$dev_video -o --width=1280 --height=720 --slice-units=4 --frame-rate=15 --iframe-period=3 --average-bitrate=3500000 > $pipe_video &"
			$VCAPTURE --dev=$dev_video -o --width=1280 --height=720 --slice-units=4 --frame-rate=15 --iframe-period=3 --average-bitrate=3500000 > $pipe_video &
			args="$args rtsp://localhost:8554/wcam$N"
		fi
	done
	$RTSPCLIENT $args >/dev/null 2>&1 &
}

fStop() {
	fMsg "Execute fStop"
	killall -9 $VCAPTURE $RTSPCLIENT $RTSPSERVER
	sleep 1.5
}


### main

case "$PCMD" in
	start)
		fInit
		fStart
		;;
	stop)
		fStop
		;;
	restart)
		fStop
		fInit
		fStart
		;;
	*)
		echo -e "\nUsage: $0 {start|stop|restart}\n"
		;;
esac

