#!/bin/bash

DIR_TARGET=/PiCAM
DIR_SCRIPT=$DIR_TARGET/script
DIR_MODULES=$DIR_TARGET/modules

#
echo "Executing prerm"

if [ -e "$DIR_MODULES" ] ; then
	$DIR_SCRIPT/deinitModule.sh
	rm -rf $DIR_MODULES
fi

