// This file is generated by Ember Desktop.  Please do not edit manually.
//
//



#include "app/framework/include/af.h"
#include "app/framework/cli/custom-cli.h"


void changeKeyCommand(void);
void echoCommand(void);
void emAfCliBsendCommand(void);
void emAfCliInfoCommand(void);
void emAfCliRawCommand(void);
void emAfCliReadCommand(void);
void emAfCliSendCommand(void);
void emAfCliSendZclIpCommand(void);
void emAfCliTimesyncCommand(void);
void emAfCliVersionCommand(void);
void emAfCliWriteCommand(void);
void emAfOtaImageDelete(void);
#if defined(EMBER_TEST)
void emAfOtaLoadFileCommand(void);
#endif
void emAfOtaPrintAllImages(void);
void emAfOtaReloadStorageDevice(void);
void emAfOtaServerPolicyPrint(void);
void emAfOtaStorageDataPrint(void);
void emAfOtaStorageInfoPrint(void);
#if defined(EMBER_TEST)
void emAfPluginFragmentationArtificialBlockDropCommand(void);
#endif
#if defined(EMBER_TEST)
void emAfPluginFragmentationSetWindowSizeCommand(void);
#endif
void emAfPluginIdentifyCliPrint(void);
void emAfPluginPriceCommonClusterConvertDurationToSecondsCli(void);
void emAfPluginPriceCommonClusterGetAdjustedStartTimeCli(void);
void emAfPluginReportingCliAdd(void);
void emAfPluginReportingCliClear(void);
void emAfPluginReportingCliPrint(void);
void emAfPluginReportingCliRemove(void);
void emAfSleepyMessageQueueCliGetCurrentInt32uMillisecondTick(void);
void emAfSleepyMessageQueueCliGetNextMessageEventTimeoutMs(void);
void emAfSleepyMessageQueueCliGetNumPendingMsg(void);
void emAfSleepyMessageQueueCliGetNumUnusedEntries(void);
void emAfSleepyMessageQueueCliGetPendingMsg(void);
void emAfSleepyMessageQueueCliGetPendingMsgId(void);
void emAfSleepyMessageQueueCliRemoveAllMsg(void);
void emAfSleepyMessageQueueCliRemoveMsgId(void);
void emAfSleepyMessageQueueCliStore(void);
void emberAfPluginAddressTableAddCommand(void);
void emberAfPluginAddressTableLookupCommand(void);
void emberAfPluginAddressTableRemoveCommand(void);
void emberAfPluginConcentratorAggregationCommand(void);
void emberAfPluginConcentratorPrintSourceRouteTable(void);
void emberAfPluginConcentratorStartDiscovery(void);
void emberAfPluginConcentratorStatus(void);
void emberAfPluginConcentratorStopDiscovery(void);
void emberAfPluginCountersClear(void);
void emberAfPluginCountersPrintCommand(void);
void emberAfPluginCountersPrintThresholdsCommand(void);
void emberAfPluginCountersResetThresholds(void);
void emberAfPluginCountersSendRequestCommand(void);
void emberAfPluginCountersSetThresholdCommand(void);
void emberAfPluginCountersSimplePrintCommand(void);
void emberAfPluginEzModeCommissioningClientCommand(void);
void emberAfPluginEzModeCommissioningServerCommand(void);
void emberAfPluginFindAndBindInitiator(void);
void emberAfPluginFindAndBindTarget(void);
void emberAfPluginGatewaySupportTimeSyncLocal(void);
void emberAfPluginSleepyMessageQueueInitCallback(void);
void emberAfPrintAllOff(void);
void emberAfPrintAllOn(void);
void emberAfPrintAttributeTable(void);
void emberAfPrintStatus(void);
void enableDisableEndpoint(void);
void endpointPrint(void);
void findJoinableNetworkCommand(void);
void findUnusedPanIdCommand(void);
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
void getSetMfgToken(void);
#endif
void helpCommand(void);
void interpanCommand(void);
void interpanLongCommand(void);
void keysClearCommand(void);
void keysDeleteCommand(void);
void keysPrintCommand(void);
void mode(void);
void networkChangeChannelCommand(void);
void networkExtendedPanIdCommand(void);
void networkFormCommand(void);
void networkIdCommand(void);
void networkInitCommand(void);
void networkJoinCommand(void);
void networkLeaveCommand(void);
void networkPermitJoinCommand(void);
void networkRejoinCommand(void);
void networkSetCommand(void);
void optionAddressTablePrintCommand(void);
void optionAddressTableSetCommand(void);
void optionApsRetryCommand(void);
void optionApsSecurityCommand(void);
void optionBindingTableClearCommand(void);
void optionBindingTablePrintCommand(void);
void optionBindingTableSetCommand(void);
void optionDiscoverCommand(void);
void optionEndDeviceBindCommand(void);
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
void optionInstallCodeCommand(void);
#endif
void optionLinkCommand(void);
void optionPrintRxCommand(void);
void optionRegisterCommand(void);
void otaImageNotifyCommand(void);
void otaSendUpgradeCommand(void);
void print(void);
void printAllLibraryStatus(void);
void printChildTable(void);
void printEvents(void);
void printInfo(void);
void printNeighborTable(void);
void printOffCommand(void);
void printOnCommand(void);
void printRouteTable(void);
void printTimeCommand(void);
void resetCommand(void);
void respond(void);
void setPolicy(void);
void timeout(void);
void zclGlobalCommandDiscoveryCommand(void);
void zclGlobalDirectionCommand(void);
void zclGlobalDiscoverCommand(void);
void zclGlobalExpectReportFromMeCommand(void);
void zclGlobalReadCommand(void);
void zclGlobalReportCommand(void);
void zclGlobalReportReadCommand(void);
void zclGlobalSendMeAReportCommand(void);
void zclGlobalWriteCommand(void);
static void zclIdentifyIdCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_COMMAND_ID);
}

void zclIdentifyOffCommand(void);
void zclIdentifyOnCommand(void);
static void zclIdentifyQueryCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_QUERY_COMMAND_ID);
}

static void zclIdentifyTriggerCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_TRIGGER_EFFECT_COMMAND_ID);
}

static void zclLockLockCommand(void) {
  zclSimpleClientCommand( ZCL_DOOR_LOCK_CLUSTER_ID,
                          ZCL_LOCK_DOOR_COMMAND_ID);
}

static void zclLockUnlockCommand(void) {
  zclSimpleClientCommand( ZCL_DOOR_LOCK_CLUSTER_ID,
                          ZCL_UNLOCK_DOOR_COMMAND_ID);
}

static void zclMeteringChgSupplyCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_CHANGE_SUPPLY_COMMAND_ID);
}

static void zclMeteringGetProfileCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_PROFILE_COMMAND_ID);
}

static void zclMeteringGetSampledDataCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_SAMPLED_DATA_COMMAND_ID);
}

static void zclMeteringGetSnapshotCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_SNAPSHOT_COMMAND_ID);
}

static void zclMeteringLocalChgSupplyCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_LOCAL_CHANGE_SUPPLY_COMMAND_ID);
}

static void zclMeteringMirrorRemovedCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_MIRROR_REMOVED_COMMAND_ID);
}

static void zclMeteringReqFastPollModeCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_REQUEST_FAST_POLL_MODE_COMMAND_ID);
}

static void zclMeteringRstLoadLimitCtrCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_RESET_LOAD_LIMIT_COUNTER_COMMAND_ID);
}

static void zclMeteringSchSnapshotCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SCHEDULE_SNAPSHOT_COMMAND_ID);
}

static void zclMeteringSetSupplyStatusCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SET_SUPPLY_STATUS_COMMAND_ID);
}

static void zclMeteringSetUncntrlFlowThresholdCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SET_UNCONTROLLED_FLOW_THRESHOLD_COMMAND_ID);
}

static void zclMeteringStartSamplingCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_START_SAMPLING_COMMAND_ID);
}

static void zclMeteringTakeSnapshotCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_TAKE_SNAPSHOT_COMMAND_ID);
}

void zclMfgCodeCommand(void);
static void zclPollControlLongCommand(void) {
  zclSimpleClientCommand( ZCL_POLL_CONTROL_CLUSTER_ID,
                          ZCL_SET_LONG_POLL_INTERVAL_COMMAND_ID);
}

static void zclPollControlShortCommand(void) {
  zclSimpleClientCommand( ZCL_POLL_CONTROL_CLUSTER_ID,
                          ZCL_SET_SHORT_POLL_INTERVAL_COMMAND_ID);
}

static void zclPollControlStopCommand(void) {
  zclSimpleClientCommand( ZCL_POLL_CONTROL_CLUSTER_ID,
                          ZCL_FAST_POLL_STOP_COMMAND_ID);
}

static void zclPowerProfileEnergyPhasesScheduleCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_ENERGY_PHASES_SCHEDULE_NOTIFICATION_COMMAND_ID);
}

static void zclPowerProfileEnergyPhasesScheduleStatesCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_ENERGY_PHASES_SCHEDULE_STATE_REQUEST_COMMAND_ID);
}

static void zclPowerProfileProfileCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_REQUEST_COMMAND_ID);
}

static void zclPowerProfileScheduleConstraintsCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_SCHEDULE_CONSTRAINTS_REQUEST_COMMAND_ID);
}

static void zclPowerProfileStateCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_STATE_REQUEST_COMMAND_ID);
}

void zclTestResponseOffCommand(void);
void zclTestResponseOnCommand(void);
void zclTimeCommand(void);
void zclXDefaultRespCommand(void);
void zdoActiveEpCommand(void);
void zdoAddClusterCommand(void);
void zdoBindCommand(void);
void zdoClearClusterCommand(void);
void zdoIeeeAddressRequestCommand(void);
void zdoLeaveRequestCommand(void);
void zdoMatchCommand(void);
void zdoMgmtBindCommand(void);
void zdoMgmtLqiCommand(void);
void zdoNetworkUpdateChannelCommand(void);
void zdoNetworkUpdateScanCommand(void);
void zdoNetworkUpdateSetCommand(void);
void zdoNodeCommand(void);
void zdoNwkAddressRequestCommand(void);
void zdoPowerDescriptorRequestCommand(void);
void zdoRouteRequestCommand(void);
void zdoSimpleCommand(void);
void zdoUnbindGroupCommand(void);
void zdoUnbindUnicastCommand(void);
PGM_P PGM zdoUnbindGroupCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The group address in the binding",
  NULL
};

PGM_P PGM zdoUnbindUnicastCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The destination EUI64 in the binding (usually the local node's EUI64",
  "The destination endpoint of the binding",
  NULL
};

EmberCommandEntry zdoUnbindCommands[] = {
  emberCommandEntryActionWithDetails("group", zdoUnbindGroupCommand, "vbuvv", "Sends an unbind request for a multicast binding to the target device.", zdoUnbindGroupCommandArguments),
  emberCommandEntryActionWithDetails("unicast", zdoUnbindUnicastCommand, "vbuvbu", "Sends an unbind request for a unicast binding to the target device.", zdoUnbindUnicastCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM zdoOutClListAddCommandArguments[] = {
  "Client cluster ids",
  NULL
};

EmberCommandEntry zdoOutClListCommands[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known client (out) clusters on this device.", zdoOutClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of client (out) clusters.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM zdoNwkUpdChanCommandArguments[] = {
  "One byte channel to change to.",
  NULL
};

PGM_P PGM zdoNwkUpdScanCommandArguments[] = {
  "Two byte short id of the target device",
  "One byte scan duration. Must be in range 0 - 5",
  "Number of scans to perform. Must be in range 1 - 8",
  NULL
};

PGM_P PGM zdoNwkUpdSetCommandArguments[] = {
  "Two byte network manager id",
  "Four byte channel mask",
  NULL
};

EmberCommandEntry zdoNwkUpdCommands[] = {
  emberCommandEntryActionWithDetails("chan", zdoNetworkUpdateChannelCommand, "u", "Sends an update channel request.", zdoNwkUpdChanCommandArguments),
  emberCommandEntryActionWithDetails("scan", zdoNetworkUpdateScanCommand, "vuv", "Performs an energy scan.", zdoNwkUpdScanCommandArguments),
  emberCommandEntryActionWithDetails("set", zdoNetworkUpdateSetCommand, "vw", "Broadcasts the ID of the new network manager and active channels.", zdoNwkUpdSetCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM zdoInClListAddCommandArguments[] = {
  "Server cluster id",
  NULL
};

EmberCommandEntry zdoInClListCommands[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known server (in) clusters on this device.", zdoInClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of server (in) clusters.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableZdoActiveCommandArguments[] = {
  "Two byte short id, destination for the active endpoint request",
  NULL
};

PGM_P PGM emberCommandTableZdoBindCommandArguments[] = {
  "Two byte destination node id",
  "Remote device's source endpoint to bind",
  "Remote endpoint to bind",
  "Cluster on which to bind",
  "Remote node EUI64",
  "Binding's dest EUI64.  Usually the local node's EUI64",
  NULL
};

PGM_P PGM emberCommandTableZdoIeeeCommandArguments[] = {
  "Short address of the device for which a long address is requested",
  NULL
};

PGM_P PGM emberCommandTableZdoLeaveCommandArguments[] = {
  "Target node ID",
  "Remove children",
  "Rejoin after leave",
  NULL
};

PGM_P PGM emberCommandTableZdoMatchCommandArguments[] = {
  "Two byte node id indicating wher",
  "Two byte profile id for the match descriptor request",
  NULL
};

PGM_P PGM emberCommandTableZdoMgmtBindCommandArguments[] = {
  "Target node ID",
  "Starting index into table query",
  NULL
};

PGM_P PGM emberCommandTableZdoMgmtLqiCommandArguments[] = {
  "Target node ID",
  "Starting index into table query",
  NULL
};

PGM_P PGM emberCommandTableZdoNodeCommandArguments[] = {
  "Two byte address for the target device.",
  NULL
};

PGM_P PGM emberCommandTableZdoNwkCommandArguments[] = {
  "IEEE address for which a short address is being requested",
  NULL
};

PGM_P PGM emberCommandTableZdoPowerCommandArguments[] = {
  "Target node ID",
  NULL
};

PGM_P PGM emberCommandTableZdoRouteCommandArguments[] = {
  "Target node ID",
  "The index of the remote node's routing table to request.",
  NULL
};

PGM_P PGM emberCommandTableZdoSimpleCommandArguments[] = {
  "Short address of the device where the simple descriptor request should ...",
  "The endpoint on the target device where the simple descriptor request  ...",
  NULL
};

EmberCommandEntry emberCommandTableZdoCommands[] = {
  emberCommandEntryActionWithDetails("active", zdoActiveEpCommand, "v", "Send an active endpoint request to the device with the given short id.", emberCommandTableZdoActiveCommandArguments),
  emberCommandEntryActionWithDetails("bind", zdoBindCommand, "vuuvbb", "Send a ZDO Bind command to a device specified in the command arguments ...", emberCommandTableZdoBindCommandArguments),
  emberCommandEntryActionWithDetails("ieee", zdoIeeeAddressRequestCommand, "v", "Request an ieee address based on a given node id.", emberCommandTableZdoIeeeCommandArguments),
  emberCommandEntrySubMenu("in-cl-list", zdoInClListCommands, ""),
  emberCommandEntryActionWithDetails("leave", zdoLeaveRequestCommand, "vuu", "Send a ZDO Management Leave command to the target device.", emberCommandTableZdoLeaveCommandArguments),
  emberCommandEntryActionWithDetails("match", zdoMatchCommand, "vv", "Sends a matchDescriptorsRequest to the given destination with the give ...", emberCommandTableZdoMatchCommandArguments),
  emberCommandEntryActionWithDetails("mgmt-bind", zdoMgmtBindCommand, "vu", "Send a ZDO MGMT-Bind (Binding Table) Request to the target device.", emberCommandTableZdoMgmtBindCommandArguments),
  emberCommandEntryActionWithDetails("mgmt-lqi", zdoMgmtLqiCommand, "vu", "Send a ZDO MGMT-LQI (LQI Table) Request to the target device.", emberCommandTableZdoMgmtLqiCommandArguments),
  emberCommandEntryActionWithDetails("node", zdoNodeCommand, "v", "Sends a node descriptor request to a given target device", emberCommandTableZdoNodeCommandArguments),
  emberCommandEntryActionWithDetails("nwk", zdoNwkAddressRequestCommand, "b", "Sends a network address request for the given IEEE address.", emberCommandTableZdoNwkCommandArguments),
  emberCommandEntrySubMenu("nwk-upd", zdoNwkUpdCommands, ""),
  emberCommandEntrySubMenu("out-cl-list", zdoOutClListCommands, ""),
  emberCommandEntryActionWithDetails("power", zdoPowerDescriptorRequestCommand, "v", "Send a ZDO Power Descriptor Request to the target device.", emberCommandTableZdoPowerCommandArguments),
  emberCommandEntryActionWithDetails("route", zdoRouteRequestCommand, "vu", "Send a ZDO route request command to the target.", emberCommandTableZdoRouteCommandArguments),
  emberCommandEntryActionWithDetails("simple", zdoSimpleCommand, "vu", "Sends out a simple descriptor request for the short address and endpoi ...", emberCommandTableZdoSimpleCommandArguments),
  emberCommandEntrySubMenu("unbind", zdoUnbindCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry testResponseCommands[] = {
  emberCommandEntryActionWithDetails("off", zclTestResponseOffCommand, "", "Sets a flag so that the application framework WILL NOT respond to the  ...", NULL),
  emberCommandEntryActionWithDetails("on", zclTestResponseOnCommand, "", "Sets a flag so that the application framework WILL respond to the next ...", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry zclTestCommands[] = {
  emberCommandEntrySubMenu("response", testResponseCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P PGM zclPowerProfileEnergyPhasesScheduleCommandArguments[] = {
  "power profile id",
  "num of scheduled phases",
  "scheduled phases",
  "",
  NULL
};

PGM_P PGM zclPowerProfileEnergyPhasesScheduleStatesCommandArguments[] = {
  "power profile id",
  NULL
};

PGM_P PGM zclPowerProfileProfileCommandArguments[] = {
  "power profile id",
  NULL
};

PGM_P PGM zclPowerProfileScheduleConstraintsCommandArguments[] = {
  "power profile id",
  NULL
};

EmberCommandEntry zclPowerProfileCommands[] = {
  emberCommandEntryActionWithDetails("energy-phases-schedule", zclPowerProfileEnergyPhasesScheduleCommand, "uub*", "The EnergyPhasesScheduleNotification Command is generated by a device  ...", zclPowerProfileEnergyPhasesScheduleCommandArguments),
  emberCommandEntryActionWithDetails("energy-phases-schedule-states", zclPowerProfileEnergyPhasesScheduleStatesCommand, "u", "The EnergyPhasesScheduleStateRequest  Command is generated by a device ...", zclPowerProfileEnergyPhasesScheduleStatesCommandArguments),
  emberCommandEntryActionWithDetails("profile", zclPowerProfileProfileCommand, "u", "The PowerProfileRequest Command is generated by a device supporting th ...", zclPowerProfileProfileCommandArguments),
  emberCommandEntryActionWithDetails("schedule-constraints", zclPowerProfileScheduleConstraintsCommand, "u", "The PowerProfileScheduleConstraintsRequest Command is generated by a d ...", zclPowerProfileScheduleConstraintsCommandArguments),
  emberCommandEntryActionWithDetails("state", zclPowerProfileStateCommand, "", "The PowerProfileStateRequest Command is generated in order to retrieve ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM zclPollControlLongCommandArguments[] = {
  "new long poll interval",
  NULL
};

PGM_P PGM zclPollControlShortCommandArguments[] = {
  "new short poll interval",
  NULL
};

EmberCommandEntry zclPollControlCommands[] = {
  emberCommandEntryActionWithDetails("long", zclPollControlLongCommand, "w", "The Set Long Poll Interval command is used to set the read only Long P ...", zclPollControlLongCommandArguments),
  emberCommandEntryActionWithDetails("short", zclPollControlShortCommand, "v", "The Set Short Poll Interval command is used to set the read only Short ...", zclPollControlShortCommandArguments),
  emberCommandEntryActionWithDetails("stop", zclPollControlStopCommand, "", "The Fast Poll Stop command is used to stop the fast poll mode initiate ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM zclMeteringChgSupplyCommandArguments[] = {
  "provider id",
  "issuer event id",
  "request date time",
  "implementation date time",
  "proposed supply status",
  "supply control bits",
  NULL
};

PGM_P PGM zclMeteringGetProfileCommandArguments[] = {
  "interval channel",
  "end time",
  "number of periods",
  NULL
};

PGM_P PGM zclMeteringGetSampledDataCommandArguments[] = {
  "sample id",
  "earliest sample time",
  "sample type",
  "number of samples",
  NULL
};

PGM_P PGM zclMeteringGetSnapshotCommandArguments[] = {
  "earliest start time",
  "latest end time",
  "snapshot offset",
  "snapshot cause",
  NULL
};

PGM_P PGM zclMeteringLocalChgSupplyCommandArguments[] = {
  "proposed supply status",
  NULL
};

PGM_P PGM zclMeteringMirrorRemovedCommandArguments[] = {
  "endpoint id",
  NULL
};

PGM_P PGM zclMeteringReqFastPollModeCommandArguments[] = {
  "fast poll update period",
  "duration",
  NULL
};

PGM_P PGM zclMeteringRstLoadLimitCtrCommandArguments[] = {
  "provider id",
  "issuer event id",
  NULL
};

PGM_P PGM zclMeteringSchSnapshotCommandArguments[] = {
  "issuer event id",
  "command index",
  "command count",
  "snapshot schedule payload",
  "",
  NULL
};

PGM_P PGM zclMeteringSetSupplyStatusCommandArguments[] = {
  "issuer event id",
  "supply tamper state",
  "supply depletion state",
  "supply uncontrolled flow state",
  "load limit supply state",
  NULL
};

PGM_P PGM zclMeteringSetUncntrlFlowThresholdCommandArguments[] = {
  "provider id",
  "issuer event id",
  "uncontrolled flow threshold",
  "unit of measure",
  "multiplier",
  "divisor",
  "stabilisation period",
  "measurement period",
  NULL
};

PGM_P PGM zclMeteringStartSamplingCommandArguments[] = {
  "issuer event id",
  "start sampling time",
  "sample type",
  "sample request interval",
  "max number of samples",
  NULL
};

PGM_P PGM zclMeteringTakeSnapshotCommandArguments[] = {
  "snapshot cause",
  NULL
};

EmberCommandEntry zclMeteringCommands[] = {
  emberCommandEntryActionWithDetails("chg-supply", zclMeteringChgSupplyCommand, "wwwwuu", "This command is sent from the Head-end or ESI to the Metering Device t ...", zclMeteringChgSupplyCommandArguments),
  emberCommandEntryActionWithDetails("get-profile", zclMeteringGetProfileCommand, "uwu", "The GetProfile command is generated when a client device wishes to ret ...", zclMeteringGetProfileCommandArguments),
  emberCommandEntryActionWithDetails("get-sampled-data", zclMeteringGetSampledDataCommand, "vwuv", "This command is used to request sampled data from the serve ...", zclMeteringGetSampledDataCommandArguments),
  emberCommandEntryActionWithDetails("get-snapshot", zclMeteringGetSnapshotCommand, "wwuw", "This command is used to request snapshot data from the cluster server.", zclMeteringGetSnapshotCommandArguments),
  emberCommandEntryActionWithDetails("local-chg-supply", zclMeteringLocalChgSupplyCommand, "u", "This command is a simplified version of the ChangeSupply command, inte ...", zclMeteringLocalChgSupplyCommandArguments),
  emberCommandEntryActionWithDetails("mirror-removed", zclMeteringMirrorRemovedCommand, "v", "The Mirror Removed Command allows the ESI to inform a sleepy Metering  ...", zclMeteringMirrorRemovedCommandArguments),
  emberCommandEntryActionWithDetails("req-fast-poll-mode", zclMeteringReqFastPollModeCommand, "uu", "The Request Fast Poll Mode command is generated when the metering clie ...", zclMeteringReqFastPollModeCommandArguments),
  emberCommandEntryActionWithDetails("rst-load-limit-ctr", zclMeteringRstLoadLimitCtrCommand, "ww", "The ResetLoadLimitCounter command shall cause the LoadLimitCounter att ...", zclMeteringRstLoadLimitCtrCommandArguments),
  emberCommandEntryActionWithDetails("sch-snapshot", zclMeteringSchSnapshotCommand, "wuub*", "This command is used to set up a schedule of when the device shall cre ...", zclMeteringSchSnapshotCommandArguments),
  emberCommandEntryActionWithDetails("set-supply-status", zclMeteringSetSupplyStatusCommand, "wuuuu", "This command is used to specify the required status of the supply foll ...", zclMeteringSetSupplyStatusCommandArguments),
  emberCommandEntryActionWithDetails("set-uncntrl-flow-threshold", zclMeteringSetUncntrlFlowThresholdCommand, "wwvuvvuv", "This command is used to update the 'Uncontrolled Flow Rate' configurat ...", zclMeteringSetUncntrlFlowThresholdCommandArguments),
  emberCommandEntryActionWithDetails("start-sampling", zclMeteringStartSamplingCommand, "wwuvv", "The sampling mechanism allows a set of samples of the specified type o ...", zclMeteringStartSamplingCommandArguments),
  emberCommandEntryActionWithDetails("take-snapshot", zclMeteringTakeSnapshotCommand, "w", "This command is used to instruct the cluster server to take a single s ...", zclMeteringTakeSnapshotCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM zclLockLockCommandArguments[] = {
  "pin",
  NULL
};

PGM_P PGM zclLockUnlockCommandArguments[] = {
  "pin",
  NULL
};

EmberCommandEntry zclLockCommands[] = {
  emberCommandEntryActionWithDetails("lock", zclLockLockCommand, "b", "Locks the door", zclLockLockCommandArguments),
  emberCommandEntryActionWithDetails("unlock", zclLockUnlockCommand, "b", "Unlocks the door", zclLockUnlockCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM zclIdentifyIdCommandArguments[] = {
  "identify time",
  NULL
};

PGM_P PGM zclIdentifyOffCommandArguments[] = {
  "The endpoint on which to stop identifying",
  NULL
};

PGM_P PGM zclIdentifyOnCommandArguments[] = {
  "The endpoint on the device which should begin identifying",
  "The number of seconds to spend identifying",
  NULL
};

PGM_P PGM zclIdentifyTriggerCommandArguments[] = {
  "effect id",
  "effect variant",
  NULL
};

EmberCommandEntry zclIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("id", zclIdentifyIdCommand, "v", "Command description for Identify", zclIdentifyIdCommandArguments),
  emberCommandEntryActionWithDetails("off", zclIdentifyOffCommand, "u", "Creates a message payload for a command that turns identifying off on  ...", zclIdentifyOffCommandArguments),
  emberCommandEntryActionWithDetails("on", zclIdentifyOnCommand, "uv", "Creates the payload for an over the air message that turns identifying ...", zclIdentifyOnCommandArguments),
  emberCommandEntryActionWithDetails("query", zclIdentifyQueryCommand, "", "Command description for IdentifyQuery", NULL),
  emberCommandEntryActionWithDetails("trigger", zclIdentifyTriggerCommand, "uu", "Command description for TriggerEffect", zclIdentifyTriggerCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM zclGlobalDirectionCommandArguments[] = {
  "The direction for global commands, 0 = client to server, 1 = server to ...",
  NULL
};

PGM_P PGM zclGlobalDiscComGenCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};

PGM_P PGM zclGlobalDiscComRecCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};

PGM_P PGM zclGlobalDiscoverCommandArguments[] = {
  "The cluster id of the cluster to discover.",
  "The attribute id of the attribute to read during discovery.",
  "Max number of discovery responses.",
  NULL
};

PGM_P PGM zclGlobalExpectReportFromMeCommandArguments[] = {
  "The cluster id for the requested report.",
  "The attribute id for the requested report.",
  "Maximum amount of time between reports.",
  NULL
};

PGM_P PGM zclGlobalNwriteCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

PGM_P PGM zclGlobalReadCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  NULL
};

PGM_P PGM zclGlobalReportCommandArguments[] = {
  "The desired endpoint.",
  "The cluster id.",
  "The attribute id.",
  "The mask.",
  NULL
};

PGM_P PGM zclGlobalReportReadCommandArguments[] = {
  "The cluster id to read from.",
  "The attribute id to read from.",
  "0 for client-to-server, 1 for server-to-client.",
  NULL
};

PGM_P PGM zclGlobalSendMeAReportCommandArguments[] = {
  "The cluster id of the requested report.",
  "The attribute id for requested report.",
  "The two byte ZigBee type value for the requested report.",
  "Minimum number of seconds between reports.",
  "Maximum number of seconds between reports.",
  "Amount of change to trigger a report.",
  NULL
};

PGM_P PGM zclGlobalUwriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

PGM_P PGM zclGlobalWriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

EmberCommandEntry zclGlobalCommands[] = {
  emberCommandEntryActionWithDetails("direction", zclGlobalDirectionCommand, "u", "Sets the direction for global commands, either client to server or ser ...", zclGlobalDirectionCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-gen", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Generated command with associated values.", zclGlobalDiscComGenCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-rec", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Received command with associated values.", zclGlobalDiscComRecCommandArguments),
  emberCommandEntryActionWithDetails("discover", zclGlobalDiscoverCommand, "vvu", "Creates discovery message for devices with the associated cluster and  ...", zclGlobalDiscoverCommandArguments),
  emberCommandEntryActionWithDetails("expect-report-from-me", zclGlobalExpectReportFromMeCommand, "vvv", "Create a expect-report-from-me message with associated values.", zclGlobalExpectReportFromMeCommandArguments),
  emberCommandEntryActionWithDetails("nwrite", zclGlobalWriteCommand, "vvub", "Creates a global write command message to write to the cluster and att ...", zclGlobalNwriteCommandArguments),
  emberCommandEntryActionWithDetails("read", zclGlobalReadCommand, "vv", "Creates a global read command message to read from the cluster and att ...", zclGlobalReadCommandArguments),
  emberCommandEntryActionWithDetails("report", zclGlobalReportCommand, "uvvu", "", zclGlobalReportCommandArguments),
  emberCommandEntryActionWithDetails("report-read", zclGlobalReportReadCommand, "vvu", "Creates a global read reporting command for the associated cluster, at ...", zclGlobalReportReadCommandArguments),
  emberCommandEntryActionWithDetails("send-me-a-report", zclGlobalSendMeAReportCommand, "vvuvvb", "Creates a global send me a report command for the associated values.", zclGlobalSendMeAReportCommandArguments),
  emberCommandEntryActionWithDetails("uwrite", zclGlobalWriteCommand, "vvub", "Creates a global write undivided command message to write to the clust ...", zclGlobalUwriteCommandArguments),
  emberCommandEntryActionWithDetails("write", zclGlobalWriteCommand, "vvwb", "Creates a global write command message to write to the cluster and att ...", zclGlobalWriteCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableZclMfgCodeCommandArguments[] = {
  "Manufacturer Specific Id",
  NULL
};

PGM_P PGM emberCommandTableZclTimeCommandArguments[] = {
  "ZigBee UTC time, number of seconds since the year 2000",
  NULL
};

PGM_P PGM emberCommandTableZclXDefaultRespCommandArguments[] = {
  "boolean value indicating whether the disable default response bit is s ...",
  NULL
};

EmberCommandEntry emberCommandTableZclCommands[] = {
  emberCommandEntrySubMenu("global", zclGlobalCommands, ""),
  emberCommandEntrySubMenu("identify", zclIdentifyCommands, ""),
  emberCommandEntrySubMenu("lock", zclLockCommands, ""),
  emberCommandEntrySubMenu("metering", zclMeteringCommands, ""),
  emberCommandEntryActionWithDetails("mfg-code", zclMfgCodeCommand, "v", "Sets the two byte manufacturer specific identifier to use for the next ...", emberCommandTableZclMfgCodeCommandArguments),
  emberCommandEntrySubMenu("poll-control", zclPollControlCommands, ""),
  emberCommandEntrySubMenu("power-profile", zclPowerProfileCommands, ""),
  emberCommandEntrySubMenu("test", zclTestCommands, ""),
  emberCommandEntryActionWithDetails("time", zclTimeCommand, "w", "Cli command to call emberAfSetTime function documented in af.h", emberCommandTableZclTimeCommandArguments),
  emberCommandEntryActionWithDetails("x-default-resp", zclXDefaultRespCommand, "u", "Sets the Disable Default Response Frame Control bit to use for the nex ...", emberCommandTableZclXDefaultRespCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM securityMfgTokenSetCommandArguments[] = {
  "magic number",
  "value",
  NULL
};

EmberCommandEntry securityMfgTokenCommands[] = {
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("get", getSetMfgToken, "", "", NULL),
#endif
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("set", getSetMfgToken, "wv", "", securityMfgTokenSetCommandArguments),
#endif
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTableSecurityCommands[] = {
  emberCommandEntrySubMenu("mfg-token", securityMfgTokenCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTablePrintCommands[] = {
  emberCommandEntryActionWithDetails("attr", emberAfPrintAttributeTable, "", "Print the attribute table.", NULL),
  emberCommandEntryActionWithDetails("time", printTimeCommand, "", "Print out the time information", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginStackDiagnosticsCommands[] = {
  emberCommandEntryActionWithDetails("child-table", printChildTable, "", "Prints out the entries in the stack's child table.", NULL),
  emberCommandEntryActionWithDetails("info", printInfo, "", "Prints out general information about the state of the stack.", NULL),
  emberCommandEntryActionWithDetails("neighbor-table", printNeighborTable, "", "Prints out the entries in the stack's neighbor table.", NULL),
  emberCommandEntryActionWithDetails("route-table", printRouteTable, "", "Prints out the entries in the stack's route table.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginSleepyMessageQueueGetNumMsgCommandArguments[] = {
  "The EUI64 of the device for which the number of pending messages is be ...",
  NULL
};

PGM_P PGM pluginSleepyMessageQueueGetPendingMsgCommandArguments[] = {
  "The messageID of the message to be retrieved.",
  NULL
};

PGM_P PGM pluginSleepyMessageQueueGetPendingMsgIdCommandArguments[] = {
  "The EUI64 of the device for which the first pending message ID is bein ...",
  NULL
};

PGM_P PGM pluginSleepyMessageQueueRemainTimeCommandArguments[] = {
  "The messageID of the message whose remaining time will be reported.",
  NULL
};

PGM_P PGM pluginSleepyMessageQueueRemoveCommandArguments[] = {
  "The messageID of the message to be removed.",
  NULL
};

PGM_P PGM pluginSleepyMessageQueueRemoveAllCommandArguments[] = {
  "The EUI64 of the device whose messages should be removed.",
  NULL
};

PGM_P PGM pluginSleepyMessageQueueStoreCommandArguments[] = {
  "Message timeout, in seconds",
  "Pointer to (address of) the message payload",
  "The length of the message payload",
  "The payload ID of this message",
  "The EUI64 of the device to which the message is being sent",
  NULL
};

EmberCommandEntry pluginSleepyMessageQueueCommands[] = {
  emberCommandEntryActionWithDetails("getNumMsg", emAfSleepyMessageQueueCliGetNumPendingMsg, "b", "Get the number of pending messages for a given destination EUI64.", pluginSleepyMessageQueueGetNumMsgCommandArguments),
  emberCommandEntryActionWithDetails("getPendingMsg", emAfSleepyMessageQueueCliGetPendingMsg, "u", "Get the first pending message ID for a given destination EUI64.", pluginSleepyMessageQueueGetPendingMsgCommandArguments),
  emberCommandEntryActionWithDetails("getPendingMsgId", emAfSleepyMessageQueueCliGetPendingMsgId, "b", "Get the first pending message ID for a given destination EUI64.", pluginSleepyMessageQueueGetPendingMsgIdCommandArguments),
  emberCommandEntryActionWithDetails("init", emberAfPluginSleepyMessageQueueInitCallback, "", "Initialize the sleepy message queue.", NULL),
  emberCommandEntryActionWithDetails("remainTime", emAfSleepyMessageQueueCliGetNextMessageEventTimeoutMs, "u", "Report the remaining timeout on the message specified by the message I ...", pluginSleepyMessageQueueRemainTimeCommandArguments),
  emberCommandEntryActionWithDetails("remove", emAfSleepyMessageQueueCliRemoveMsgId, "u", "Remove the message from the queue with the given messageID.", pluginSleepyMessageQueueRemoveCommandArguments),
  emberCommandEntryActionWithDetails("removeAll", emAfSleepyMessageQueueCliRemoveAllMsg, "b", "Remove all messages from the queue with the given EUI64.", pluginSleepyMessageQueueRemoveAllCommandArguments),
  emberCommandEntryActionWithDetails("store", emAfSleepyMessageQueueCliStore, "wwvvb", "Store a message into the sleepy message queue.", pluginSleepyMessageQueueStoreCommandArguments),
  emberCommandEntryActionWithDetails("timestamp", emAfSleepyMessageQueueCliGetCurrentInt32uMillisecondTick, "", "Retrieve the current value of halCommonGetInt32uMillisecondTick().", NULL),
  emberCommandEntryActionWithDetails("unusedCnt", emAfSleepyMessageQueueCliGetNumUnusedEntries, "", "Reads the number of unused queue entries.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginReportingAddCommandArguments[] = {
  "The local endpoint from which the attribute is reported.",
  "The cluster where the attribute is located.",
  "The id of the attribute being reported.",
  "0 for client-side attributes or 1 for server-side attributes.",
  "The minimum reporting interval, measured in seconds.",
  "The maximum reporting interval, measured in seconds.",
  "The minimum change to the attribute that will result in a report being ...",
  NULL
};

PGM_P PGM pluginReportingRemoveCommandArguments[] = {
  "The index of the report to be removed.",
  NULL
};

EmberCommandEntry pluginReportingCommands[] = {
  emberCommandEntryActionWithDetails("add", emAfPluginReportingCliAdd, "uvvuvvw", "Add a new entry to the report table.", pluginReportingAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", emAfPluginReportingCliClear, "", "Clear all entries from the report table.", NULL),
  emberCommandEntryActionWithDetails("print", emAfPluginReportingCliPrint, "", "Print the report table.", NULL),
  emberCommandEntryActionWithDetails("remove", emAfPluginReportingCliRemove, "u", "Remove an entry from the report table.", pluginReportingRemoveCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginPriceCommonAdjStTCommandArguments[] = {
  "start time utc",
  "duration type",
  NULL
};

PGM_P PGM pluginPriceCommonCnvrtDurnToSecCommandArguments[] = {
  "start time utc",
  "duration",
  "duration type",
  NULL
};

EmberCommandEntry pluginPriceCommonCommands[] = {
  emberCommandEntryActionWithDetails("adj-st-t", emAfPluginPriceCommonClusterGetAdjustedStartTimeCli, "wu", "Calculates a new UTC start time value based on the duration type param ...", pluginPriceCommonAdjStTCommandArguments),
  emberCommandEntryActionWithDetails("cnvrt-durn-to-sec", emAfPluginPriceCommonClusterConvertDurationToSecondsCli, "wwu", "Converts the duration to a number of seconds based on the duration typ ...", pluginPriceCommonCnvrtDurnToSecCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginPollControlClientModeCommandArguments[] = {
  "The fast polling mode.",
  NULL
};

PGM_P PGM pluginPollControlClientRespondCommandArguments[] = {
  "The response mode.",
  NULL
};

PGM_P PGM pluginPollControlClientTimeoutCommandArguments[] = {
  "The fast polling timeout.",
  NULL
};

EmberCommandEntry pluginPollControlClientCommands[] = {
  emberCommandEntryActionWithDetails("mode", mode, "u", "Set the fast polling mode.", pluginPollControlClientModeCommandArguments),
  emberCommandEntryActionWithDetails("print", print, "", "Print the fast polling mode and timeout.", NULL),
  emberCommandEntryActionWithDetails("respond", respond, "u", "Set the response mode.", pluginPollControlClientRespondCommandArguments),
  emberCommandEntryActionWithDetails("timeout", timeout, "v", "Set the fast polling timeout.", pluginPollControlClientTimeoutCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginOtaStorageCommonDataPrintCommandArguments[] = {
  "The index of the image to print its data.",
  "The offset into the OTA image that will be printed.",
  NULL
};

PGM_P PGM pluginOtaStorageCommonDeleteCommandArguments[] = {
  "The index at which to begin bootloading the image",
  NULL
};

EmberCommandEntry pluginOtaStorageCommonCommands[] = {
  emberCommandEntryActionWithDetails("data-print", emAfOtaStorageDataPrint, "uw", "Print arbitray bytes of the OTA image on disk.", pluginOtaStorageCommonDataPrintCommandArguments),
  emberCommandEntryActionWithDetails("delete", emAfOtaImageDelete, "u", "Deletes the image at the specified index.", pluginOtaStorageCommonDeleteCommandArguments),
  emberCommandEntryActionWithDetails("printImages", emAfOtaPrintAllImages, "", "Prints the images.", NULL),
  emberCommandEntryActionWithDetails("reload", emAfOtaReloadStorageDevice, "", "Reload the storage device.", NULL),
  emberCommandEntryActionWithDetails("storage-info", emAfOtaStorageInfoPrint, "", "Print information about the storage device.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM otaServerPolicyBlockRequestCommandArguments[] = {
  "0: Send block (default), 1: Delay download once for 2 minutes, 2: Alwa ...",
  NULL
};

PGM_P PGM otaServerPolicyImageReqMinPeriodCommandArguments[] = {
  "The minimum request period in milliseconds.",
  NULL
};

PGM_P PGM otaServerPolicyPageReqMissCommandArguments[] = {
  "0: Upgrade if server has newer (default), 1: Downgrade if server has o ...",
  NULL
};

PGM_P PGM otaServerPolicyPageReqSupCommandArguments[] = {
  "0: Upgrade if server has newer (default), 1: Downgrade if server has o ...",
  NULL
};

PGM_P PGM otaServerPolicyQueryCommandArguments[] = {
  "0: Upgrade if server has newer (default), 1: Downgrade if server has o ...",
  NULL
};

PGM_P PGM otaServerPolicyUpgradeCommandArguments[] = {
  "0: Upgrade Now (default), 1: Upgrade in 2       minutes, 2: Ask me lat ...",
  NULL
};

EmberCommandEntry otaServerPolicyCommands[] = {
  emberCommandEntryActionWithDetails("blockRequest", setPolicy, "u", "Sets the policy used by the ota-server Policy Plugin when it receives  ...", otaServerPolicyBlockRequestCommandArguments),
  emberCommandEntryActionWithDetails("image-req-min-period", setPolicy, "v", "", otaServerPolicyImageReqMinPeriodCommandArguments),
  emberCommandEntryActionWithDetails("page-req-miss", setPolicy, "u", "", otaServerPolicyPageReqMissCommandArguments),
  emberCommandEntryActionWithDetails("page-req-sup", setPolicy, "u", "", otaServerPolicyPageReqSupCommandArguments),
  emberCommandEntryActionWithDetails("print", emAfOtaServerPolicyPrint, "", "Prints the polices used by the OTA Server Policy Plugin", NULL),
  emberCommandEntryActionWithDetails("query", setPolicy, "u", "Sets the policy used by the OTA Server Policy Plugin when it receives  ...", otaServerPolicyQueryCommandArguments),
  emberCommandEntryActionWithDetails("upgrade", setPolicy, "u", "Sets the policy used by the OTA Server Policy Plugin when it receives  ...", otaServerPolicyUpgradeCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginOtaServerLoadFileCommandArguments[] = {
  "The file name.",
  NULL
};

PGM_P PGM pluginOtaServerNotifyCommandArguments[] = {
  "The node ID (can be a broadcast address) to which this OTA Notify mess ...",
  "Target endpoint for the OTA Notify message (only really meaningful for ...",
  "Used to specify which parameters you want included in the OTA Notify c ...",
  "Corresponds to QueryJitter parameter in the OTA Upgrade cluster specif ...",
  "Manufacturer ID for the image being advertised (should match the mfr I ...",
  "Image type ID for the image being advertised (should match the image t ...",
  "Firmware version of the image being advertised (should match the versi ...",
  NULL
};

PGM_P PGM pluginOtaServerUpgradeCommandArguments[] = {
  "device id for the image",
  "software version for the image",
  NULL
};

EmberCommandEntry pluginOtaServerCommands[] = {
#if defined(EMBER_TEST)
  emberCommandEntryActionWithDetails("load-file", emAfOtaLoadFileCommand, "b", "Load file.", pluginOtaServerLoadFileCommandArguments),
#endif
  emberCommandEntryActionWithDetails("notify", otaImageNotifyCommand, "vuuuvvw", "Sends an OTA Image Notify message to the specified destination indicat ...", pluginOtaServerNotifyCommandArguments),
  emberCommandEntrySubMenu("policy", otaServerPolicyCommands, ""),
  emberCommandEntryActionWithDetails("upgrade", otaSendUpgradeCommand, "vu", "Instruct a device to upgrade now.", pluginOtaServerUpgradeCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("print", emAfPluginIdentifyCliPrint, "", "Print which endpoints are reporting.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginGatewayCommands[] = {
  emberCommandEntryActionWithDetails("time-sync-local", emberAfPluginGatewaySupportTimeSyncLocal, "", "This command will sync the ZCL device's local time attribute with the  ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginFragmentationArtificialBlockDropCommandArguments[] = {
  "The block number to artificially drop to force a retr ...",
  NULL
};

PGM_P PGM pluginFragmentationSetRxWindowSizeCommandArguments[] = {
  "The max number of the blocks received before an APS ack is generated.",
  NULL
};

EmberCommandEntry pluginFragmentationCommands[] = {
#if defined(EMBER_TEST)
  emberCommandEntryActionWithDetails("artificial-block-drop", emAfPluginFragmentationArtificialBlockDropCommand, "u", "Artificially drops the block number defined by the passed argument onl ...", pluginFragmentationArtificialBlockDropCommandArguments),
#endif
#if defined(EMBER_TEST)
  emberCommandEntryActionWithDetails("set-rx-window-size", emAfPluginFragmentationSetWindowSizeCommand, "u", "Sets the receive window siz ...", pluginFragmentationSetRxWindowSizeCommandArguments),
#endif
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginFindAndBindCommands[] = {
  emberCommandEntryActionWithDetails("initiator", emberAfPluginFindAndBindInitiator, "", "Makes this node start the initiator part of the finding and binding pr ...", NULL),
  emberCommandEntryActionWithDetails("target", emberAfPluginFindAndBindTarget, "", "Makes this node start identifying as a target for binding with an init ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginEzmodeCommissioningClientCommandArguments[] = {
  "The local endpoint.",
  "::EMBER_AF_EZMODE_COMMISSIONING_SERVER_TO_CLIENT or ::EMBER_AF_EZMODE_ ...",
  "A list of cluster ids.",
  "",
  NULL
};

PGM_P PGM pluginEzmodeCommissioningServerCommandArguments[] = {
  "The local endpoint.",
  "The identify time in seconds.",
  NULL
};

EmberCommandEntry pluginEzmodeCommissioningCommands[] = {
  emberCommandEntryActionWithDetails("client", emberAfPluginEzModeCommissioningClientCommand, "uuv*", "Start EZ-Mode client commissioning.", pluginEzmodeCommissioningClientCommandArguments),
  emberCommandEntryActionWithDetails("server", emberAfPluginEzModeCommissioningServerCommand, "uv", "Start EZ-Mode server commissioning.", pluginEzmodeCommissioningServerCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginCountersSetThresholdCommandArguments[] = {
  "type of counter",
  "Threshold Value",
  NULL
};

EmberCommandEntry pluginCountersCommands[] = {
  emberCommandEntryActionWithDetails("clear", emberAfPluginCountersClear, "", "Clear all counter values.", NULL),
  emberCommandEntryActionWithDetails("print", emberAfPluginCountersPrintCommand, "", "Print all counter values and clear them.", NULL),
  emberCommandEntryActionWithDetails("print-thresholds", emberAfPluginCountersPrintThresholdsCommand, "", "Prints the thresholds of all the counters.", NULL),
  emberCommandEntryActionWithDetails("reset-threshold", emberAfPluginCountersResetThresholds, "", "Resets all thresholds values to 0xFFFF.", NULL),
  emberCommandEntryActionWithDetails("send-request", emberAfPluginCountersSendRequestCommand, "", "Sends a request for ota counters", NULL),
  emberCommandEntryActionWithDetails("set-threshold", emberAfPluginCountersSetThresholdCommand, "uv", "Set a threshold value for a particular type of counter.", pluginCountersSetThresholdCommandArguments),
  emberCommandEntryActionWithDetails("simple-print", emberAfPluginCountersSimplePrintCommand, "", "Print all counter values.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginConcentratorCommands[] = {
  emberCommandEntryActionWithDetails("agg", emberAfPluginConcentratorAggregationCommand, "", "(Requires Concentrator Support to be enabled on this devic ...", NULL),
  emberCommandEntryActionWithDetails("print-table", emberAfPluginConcentratorPrintSourceRouteTable, "", "Print the source route table.", NULL),
  emberCommandEntryActionWithDetails("start", emberAfPluginConcentratorStartDiscovery, "", "Starts the periodic broadcast of MTORRs", NULL),
  emberCommandEntryActionWithDetails("status", emberAfPluginConcentratorStatus, "", "Prints current status and configured parameters of the concentrator", NULL),
  emberCommandEntryActionWithDetails("stop", emberAfPluginConcentratorStopDiscovery, "", "Stops the periodic broadcast of MTORRs", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM pluginAddressTableAddCommandArguments[] = {
  "Entry to be added.",
  NULL
};

PGM_P PGM pluginAddressTableLookupCommandArguments[] = {
  "Entry to be looked up.",
  NULL
};

PGM_P PGM pluginAddressTableRemoveCommandArguments[] = {
  "Entry to be removed.",
  NULL
};

EmberCommandEntry pluginAddressTableCommands[] = {
  emberCommandEntryActionWithDetails("add", emberAfPluginAddressTableAddCommand, "b", "Add an entry to the address table.", pluginAddressTableAddCommandArguments),
  emberCommandEntryActionWithDetails("lookup", emberAfPluginAddressTableLookupCommand, "b", "Lookup an entry in the address table.", pluginAddressTableLookupCommandArguments),
  emberCommandEntryActionWithDetails("remove", emberAfPluginAddressTableRemoveCommand, "b", "Remove an entry from the address table.", pluginAddressTableRemoveCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTablePluginCommands[] = {
  emberCommandEntrySubMenu("address-table", pluginAddressTableCommands, ""),
  emberCommandEntrySubMenu("concentrator", pluginConcentratorCommands, ""),
  emberCommandEntrySubMenu("counters", pluginCountersCommands, ""),
  emberCommandEntrySubMenu("ezmode-commissioning", pluginEzmodeCommissioningCommands, ""),
  emberCommandEntrySubMenu("find-and-bind", pluginFindAndBindCommands, ""),
  emberCommandEntrySubMenu("fragmentation", pluginFragmentationCommands, ""),
  emberCommandEntrySubMenu("gateway", pluginGatewayCommands, ""),
  emberCommandEntrySubMenu("identify", pluginIdentifyCommands, ""),
  emberCommandEntrySubMenu("ota-server", pluginOtaServerCommands, ""),
  emberCommandEntrySubMenu("ota-storage-common", pluginOtaStorageCommonCommands, ""),
  emberCommandEntrySubMenu("poll-control-client", pluginPollControlClientCommands, ""),
  emberCommandEntrySubMenu("price-common", pluginPriceCommonCommands, ""),
  emberCommandEntrySubMenu("reporting", pluginReportingCommands, ""),
  emberCommandEntrySubMenu("sleepy-message-queue", pluginSleepyMessageQueueCommands, ""),
  emberCommandEntrySubMenu("stack-diagnostics", pluginStackDiagnosticsCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry securityApsCommands[] = {
  emberCommandEntryActionWithDetails("off", optionApsSecurityCommand, "", "Turns aps security off", NULL),
  emberCommandEntryActionWithDetails("on", optionApsSecurityCommand, "", "Turns aps security on", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionSecurityCommands[] = {
  emberCommandEntrySubMenu("aps", securityApsCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionPrintRxMsgsCommands[] = {
  emberCommandEntryActionWithDetails("disable", optionPrintRxCommand, "", "Disable the printing of received messages.", NULL),
  emberCommandEntryActionWithDetails("enable", optionPrintRxCommand, "", "Enable the printing of received messages.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM optionBindingTableSetCommandArguments[] = {
  "one byte index into the binding table",
  "cluster id to send with the discovery message",
  "local endpoint to bind",
  "remote endpoint to bind",
  "8 byte IEEE address provided big endian",
  NULL
};

EmberCommandEntry optionBindingTableCommands[] = {
  emberCommandEntryActionWithDetails("clear", optionBindingTableClearCommand, "", "Clear the binding table", NULL),
  emberCommandEntryActionWithDetails("print", optionBindingTablePrintCommand, "", "Prints out the binding table to the command line.", NULL),
  emberCommandEntryActionWithDetails("set", optionBindingTableSetCommand, "uvuub", "Set a binding table entry for the arguments specified.", optionBindingTableSetCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionApsretryCommands[] = {
  emberCommandEntryActionWithDetails("default", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("off", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("on", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM optionAddressTableSetCommandArguments[] = {
  "one byte index into the address table",
  "IEEE address to enter into the address table",
  "two byte node id to enter into the address table",
  NULL
};

EmberCommandEntry optionAddressTableCommands[] = {
  emberCommandEntryActionWithDetails("print", optionAddressTablePrintCommand, "", "Prints the address table.", NULL),
  emberCommandEntryActionWithDetails("set", optionAddressTableSetCommand, "ubv", "Set an entry in the address table according to the arguments specified", optionAddressTableSetCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableOptionDiscCommandArguments[] = {
  "the profile id to send with the discovery message",
  "cluster id to send with the discovery message",
  NULL
};

PGM_P PGM emberCommandTableOptionEdbCommandArguments[] = {
  "The local endpoint whose simple descriptor will be used to create the  ...",
  NULL
};

PGM_P PGM emberCommandTableOptionInstallCodeCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "install code including two-byte, little-endian CRC",
  NULL
};

PGM_P PGM emberCommandTableOptionLinkCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "link key to enter into the table",
  NULL
};

EmberCommandEntry emberCommandTableOptionCommands[] = {
  emberCommandEntrySubMenu("address-table", optionAddressTableCommands, ""),
  emberCommandEntrySubMenu("apsretry", optionApsretryCommands, ""),
  emberCommandEntrySubMenu("binding-table", optionBindingTableCommands, ""),
  emberCommandEntryActionWithDetails("disc", optionDiscoverCommand, "vv", "Sends a ZDO Match Descriptor Request for the server side of the specif ...", emberCommandTableOptionDiscCommandArguments),
  emberCommandEntryActionWithDetails("edb", optionEndDeviceBindCommand, "u", "Sends a ZDO End Device Bind Request using the given local endpoint.", emberCommandTableOptionEdbCommandArguments),
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("install-code", optionInstallCodeCommand, "ubb", "Derives a link key from an install code and sets it in the link key ta ...", emberCommandTableOptionInstallCodeCommandArguments),
#endif
  emberCommandEntryActionWithDetails("link", optionLinkCommand, "ubb", "Sets a link key in the link key tabl ...", emberCommandTableOptionLinkCommandArguments),
  emberCommandEntrySubMenu("print-rx-msgs", optionPrintRxMsgsCommands, ""),
  emberCommandEntryActionWithDetails("register", optionRegisterCommand, "", "Initiates Smart Energy Registration including Key Establishmen ...", NULL),
  emberCommandEntrySubMenu("security", optionSecurityCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry networkFindCommands[] = {
  emberCommandEntryActionWithDetails("joinable", findJoinableNetworkCommand, "", "Begins a search for a joinable networ ...", NULL),
  emberCommandEntryActionWithDetails("unused", findUnusedPanIdCommand, "", "Begins a search for an unused Channel and Pan I ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableNetworkBroadPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};

PGM_P PGM emberCommandTableNetworkChangeChannelCommandArguments[] = {
  "The channel to change to.",
  NULL
};

PGM_P PGM emberCommandTableNetworkExtpanidCommandArguments[] = {
  "The bytes for the extended pan id",
  NULL
};

PGM_P PGM emberCommandTableNetworkFormCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};

PGM_P PGM emberCommandTableNetworkJoinCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};

PGM_P PGM emberCommandTableNetworkPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};

PGM_P PGM emberCommandTableNetworkRejoinCommandArguments[] = {
  "Boolean indicating whether the device can rejoin secure or no ...",
  "4 byte channel mask which should be used to search for the network to  ...",
  NULL
};

PGM_P PGM emberCommandTableNetworkSetCommandArguments[] = {
  "The network index to use for CLI commands",
  NULL
};

EmberCommandEntry emberCommandTableNetworkCommands[] = {
  emberCommandEntryActionWithDetails("broad-pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds AND broadc ...", emberCommandTableNetworkBroadPjoinCommandArguments),
  emberCommandEntryActionWithDetails("change-channel", networkChangeChannelCommand, "u", "Attempts to change device over to a different channel given in the cha ...", emberCommandTableNetworkChangeChannelCommandArguments),
  emberCommandEntryActionWithDetails("extpanid", networkExtendedPanIdCommand, "b", "Write the extended pan id for the device.", emberCommandTableNetworkExtpanidCommandArguments),
  emberCommandEntrySubMenu("find", networkFindCommands, ""),
  emberCommandEntryActionWithDetails("form", networkFormCommand, "usv", "Create a network on the given channel, power and panId.", emberCommandTableNetworkFormCommandArguments),
  emberCommandEntryActionWithDetails("id", networkIdCommand, "", "Prints the current Node ID, EUI64, and Pan ID.", NULL),
  emberCommandEntryActionWithDetails("init", networkInitCommand, "", "Initialize a network; this is a test command used for tc-swap-out test ...", NULL),
  emberCommandEntryActionWithDetails("join", networkJoinCommand, "usv", "Join an existing network on the given channel, power and panId.", emberCommandTableNetworkJoinCommandArguments),
  emberCommandEntryActionWithDetails("leave", networkLeaveCommand, "", "Leave the current network.", NULL),
  emberCommandEntryActionWithDetails("pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds", emberCommandTableNetworkPjoinCommandArguments),
  emberCommandEntryActionWithDetails("rejoin", networkRejoinCommand, "uw", "Rejoin an existing network in a secure or insecure manner.", emberCommandTableNetworkRejoinCommandArguments),
  emberCommandEntryActionWithDetails("set", networkSetCommand, "u", "Set the network index used by all future CLI command ...", emberCommandTableNetworkSetCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableKeysDeleteCommandArguments[] = {
  "index into the security key table",
  NULL
};

EmberCommandEntry emberCommandTableKeysCommands[] = {
  emberCommandEntryActionWithDetails("clear", keysClearCommand, "", "Clear all security keys", NULL),
  emberCommandEntryActionWithDetails("delete", keysDeleteCommand, "u", "Delete a security key from a given index", emberCommandTableKeysDeleteCommandArguments),
  emberCommandEntryActionWithDetails("print", keysPrintCommand, "", "Print all security keys out to the command line.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableInterpanGroupCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};

PGM_P PGM emberCommandTableInterpanLongCommandArguments[] = {
  "long ieee address to send the interpan message to",
  "two byte destination PA ID",
  "two byte destination profile ID",
  "two byte options",
  NULL
};

PGM_P PGM emberCommandTableInterpanShortCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};

EmberCommandEntry emberCommandTableInterpanCommands[] = {
  emberCommandEntryActionWithDetails("group", interpanCommand, "vvv", "send an interpan message to a group id.", emberCommandTableInterpanGroupCommandArguments),
  emberCommandEntryActionWithDetails("long", interpanLongCommand, "bvvv", "Send an interpan message to a long address (8 byte eui64)", emberCommandTableInterpanLongCommandArguments),
  emberCommandEntryActionWithDetails("short", interpanCommand, "vvv", "Send an interpan message to a short id.", emberCommandTableInterpanShortCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableEndpointDisableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};

PGM_P PGM emberCommandTableEndpointEnableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};

EmberCommandEntry emberCommandTableEndpointCommands[] = {
  emberCommandEntryActionWithDetails("disable", enableDisableEndpoint, "u", "Disable the endpoint for processing ZCL messages.", emberCommandTableEndpointDisableCommandArguments),
  emberCommandEntryActionWithDetails("enable", enableDisableEndpoint, "u", "Enable the endpoint for processing ZCL messages.", emberCommandTableEndpointEnableCommandArguments),
  emberCommandEntryActionWithDetails("print", endpointPrint, "", "Print the status of all the endpoints.", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableDebugprintOffCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};

PGM_P PGM emberCommandTableDebugprintOnCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};

EmberCommandEntry emberCommandTableDebugprintCommands[] = {
  emberCommandEntryActionWithDetails("all_off", emberAfPrintAllOff, "", "Turns off all debug printing", NULL),
  emberCommandEntryActionWithDetails("all_on", emberAfPrintAllOn, "", "Turns on all compiled in debug printing", NULL),
  emberCommandEntryActionWithDetails("off", printOffCommand, "u", "Turns off compiled in debug printing for a specific debug printing are ...", emberCommandTableDebugprintOffCommandArguments),
  emberCommandEntryActionWithDetails("on", printOnCommand, "u", "Turns on compiled in debug printing for a specific debug printing area ...", emberCommandTableDebugprintOnCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPrintStatus, "", "Prints out the current settings for debug printing on the device", NULL),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableChangekeyLinkCommandArguments[] = {
  "The link key provided as a 16 byte array",
  NULL
};

PGM_P PGM emberCommandTableChangekeyNetworkCommandArguments[] = {
  "The network key provided as a 16 byte array",
  NULL
};

EmberCommandEntry emberCommandTableChangekeyCommands[] = {
  emberCommandEntryActionWithDetails("link", changeKeyCommand, "b", "Change the link key to the one provided in the 16 byte array argument  ...", emberCommandTableChangekeyLinkCommandArguments),
  emberCommandEntryActionWithDetails("network", changeKeyCommand, "b", "Change the network key to the 16 byte array provided as an argument to ...", emberCommandTableChangekeyNetworkCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P PGM emberCommandTableBsendCommandArguments[] = {
  "source endpoint to send a binding based message from",
  NULL
};

PGM_P PGM emberCommandTableEchoCommandArguments[] = {
  "boolean indicating whether to turn echo on (1) or off (0)",
  NULL
};

PGM_P PGM emberCommandTableRawCommandArguments[] = {
  "two byte cluster id",
  "two byte short id of the time server",
  NULL
};

PGM_P PGM emberCommandTableReadCommandArguments[] = {
  "endpoint of the attribute to read",
  "cluster id of the attribute to read",
  "attribute id of the attribute to read",
  "direction mask of the attribute to read (client=0 or server=1)",
  NULL
};

PGM_P PGM emberCommandTableSendCommandArguments[] = {
  "short id of the device to send the message to",
  "The endpoint to send the message from",
  "The endpoint to send the message to",
  NULL
};

PGM_P PGM emberCommandTableSendMulticastCommandArguments[] = {
  "group id of the multicast group to send the message to",
  "The endpoint to send the message from",
  NULL
};

PGM_P PGM emberCommandTableSendZclIpCommandArguments[] = {
  "Destination EUI64",
  "sourceEndpoint",
  "Destination Endpoint",
  NULL
};

PGM_P PGM emberCommandTableTimesyncCommandArguments[] = {
  "two byte short id of the time server",
  "source endpoint to send time sync from",
  "destination endpoint to expect response on",
  NULL
};

PGM_P PGM emberCommandTableWriteCommandArguments[] = {
  "endpoint of the attribute to write",
  "cluster id of the attribute to write",
  "attribute id of the attribute to write",
  "direction mask of the attribute to write (client=0 or server=1)",
  "the attribute type as listed in the generated file attribute-type.h",
  "string of bytes you wish to write into the attribute table.",
  NULL
};

EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryActionWithDetails("bsend", emAfCliBsendCommand, "u", "send using a binding based on the clusterId in the globalApsFrame and  ...", emberCommandTableBsendCommandArguments),
  emberCommandEntrySubMenu("changekey", emberCommandTableChangekeyCommands, ""),
  emberCommandEntrySubMenu("debugprint", emberCommandTableDebugprintCommands, ""),
  emberCommandEntryActionWithDetails("echo", echoCommand, "u", "Turns echo on the command line on or off depending on the argument", emberCommandTableEchoCommandArguments),
  emberCommandEntrySubMenu("endpoint", emberCommandTableEndpointCommands, ""),
  emberCommandEntryActionWithDetails("events", printEvents, "", "Print the list of timer events.", NULL),
  emberCommandEntryActionWithDetails("help", helpCommand, "", "Prints out the cli command options for the device", NULL),
  emberCommandEntryActionWithDetails("info", emAfCliInfoCommand, "", "Gives information about the local node", NULL),
  emberCommandEntrySubMenu("interpan", emberCommandTableInterpanCommands, ""),
  emberCommandEntrySubMenu("keys", emberCommandTableKeysCommands, ""),
  emberCommandEntryActionWithDetails("libs", printAllLibraryStatus, "", "Lists which optional libraries of the stack are implemented on this de ...", NULL),
  emberCommandEntrySubMenu("network", emberCommandTableNetworkCommands, ""),
  emberCommandEntrySubMenu("option", emberCommandTableOptionCommands, ""),
  emberCommandEntrySubMenu("plugin", emberCommandTablePluginCommands, ""),
  emberCommandEntrySubMenu("print", emberCommandTablePrintCommands, ""),
  emberCommandEntryActionWithDetails("raw", emAfCliRawCommand, "vb", "Creates a message by specifying the raw byte ...", emberCommandTableRawCommandArguments),
  emberCommandEntryActionWithDetails("read", emAfCliReadCommand, "uvvu", "Read an attribute from the local attribute tabl ...", emberCommandTableReadCommandArguments),
  emberCommandEntryActionWithDetails("reset", resetCommand, "", "resets the device", NULL),
  emberCommandEntrySubMenu("security", emberCommandTableSecurityCommands, ""),
  emberCommandEntryActionWithDetails("send", emAfCliSendCommand, "vuu", "Send a pre-buffered message from a given endpoint to an endpoint on a  ...", emberCommandTableSendCommandArguments),
  emberCommandEntryActionWithDetails("send_multicast", emAfCliSendCommand, "vu", "Send a pre-buffered multicast message to a given group id from a given ...", emberCommandTableSendMulticastCommandArguments),
  emberCommandEntryActionWithDetails("send_zcl_ip", emAfCliSendZclIpCommand, "buu", "Send a ZCL message over ZCL-IP", emberCommandTableSendZclIpCommandArguments),
  emberCommandEntryActionWithDetails("timesync", emAfCliTimesyncCommand, "vuu", "This sends a read attr for the time of the device specifie ...", emberCommandTableTimesyncCommandArguments),
  emberCommandEntryActionWithDetails("version", emAfCliVersionCommand, "", "Shows the version of the software", NULL),
  emberCommandEntryActionWithDetails("write", emAfCliWriteCommand, "uvvuub", "Write an attribute value into the local attribute table", emberCommandTableWriteCommandArguments),
  emberCommandEntrySubMenu("zcl", emberCommandTableZclCommands, ""),
  emberCommandEntrySubMenu("zdo", emberCommandTableZdoCommands, ""),
  CUSTOM_COMMANDS
  emberCommandEntryTerminator()
};



