
ifndef	BASEDIR
BASEDIR		:=$(shell pwd)/..
endif
include $(BASEDIR)/Rules.mk

#------------------------------------------------------------------------------

#SUBDIRS	:= hello.c hello.cpp
SUBDIRS		:=	vcapture \
				rtspserver \
				portmap \
				zbember

#------------------------------------------------------------------------------

include $(BUILDDIR)/Rules.common
