#
#------------------------------------------------------------------------------

ifndef	BASEDIR
BASEDIR			:=$(shell pwd)
endif
include $(BASEDIR)/Rules.mk

#------------------------------------------------------------------------------

SUBDIRS			:= include \
				   external \
				   utils \
				   scripts
						
#------------------------------------------------------------------------------

include $(BUILDDIR)/Rules.common

